### ISSUE TITLE
kutilities module!!!

### ISSUE THREAD

**Issue by asadmohd1995** [sismetanin/emosense-semeval2019-task3-emocontext#1]
ModuleNotFoundError: No module named 'kutilities'
Collecting kutilities
ERROR: Could not find a version that satisfies the requirement kutilities (from versions: none)
ERROR: No matching distribution found for kutilities

Also dev and test files are missing
plz HELP!!!!

**Comment by sismetanin** [comment]
Hi!

> ModuleNotFoundError: No module named 'kutilities'

Please use the following command to install [kutilities](https://github.com/cbaziotis/keras-utilities) module:
`pip install keras-utilities`

> Also dev and test files are missing

Data provided by Microsoft. It can be found in the [official LinkedIn group](https://www.linkedin.com/feed/update/urn:li:activity:6439879151053836288/) of the EmoContext competition. Unfortunately, we are unable to publish data in this repository due to the license agreement of the competition.

You can find a description of the approach in the [original SemEval-2019 paper.](https://www.aclweb.org/anthology/S19-2034/) Some implementation details can be also found in the [Habr](https://habr.com/ru/company/mailru/blog/439850/) and [Medium](https://towardsdatascience.com/contextual-emotion-detection-in-textual-conversations-using-neural-networks-381e3d8490c4) articles.
